/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mantenimiento;

/**
 *
 * @author axel
 */
public class MenuMantenimiento extends javax.swing.JFrame {

    /**
     * Creates new form MenuMantenimiento
     */
    public MenuMantenimiento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPMenu = new javax.swing.JDesktopPane();
        JMBMenu = new javax.swing.JMenuBar();
        JMRegistro = new javax.swing.JMenu();
        JMAltaE = new javax.swing.JMenuItem();
        JMMantenimiento = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        JMCrearM = new javax.swing.JMenuItem();
        JMAsignacion = new javax.swing.JMenu();
        JmVehicular = new javax.swing.JMenuItem();
        JMProveedores = new javax.swing.JMenu();
        JMBuscarP = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        JMCompraP = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        JMCompras = new javax.swing.JMenu();
        JMCompraM = new javax.swing.JMenu();
        JMElaborar = new javax.swing.JMenuItem();
        JmRMotos = new javax.swing.JMenu();
        JmiRegistrarM = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu ");

        JMRegistro.setText("Registrar Empleado ");

        JMAltaE.setText("Empleado");
        JMAltaE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMAltaEActionPerformed(evt);
            }
        });
        JMRegistro.add(JMAltaE);

        JMBMenu.add(JMRegistro);

        JMMantenimiento.setText("Mantenimiento ");
        JMMantenimiento.setToolTipText("");

        jMenuItem4.setText("Editar ");
        JMMantenimiento.add(jMenuItem4);

        JMCrearM.setText("Elaborar");
        JMCrearM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMCrearMActionPerformed(evt);
            }
        });
        JMMantenimiento.add(JMCrearM);

        JMBMenu.add(JMMantenimiento);

        JMAsignacion.setText("Asignacion ");

        JmVehicular.setText("Vehicular");
        JmVehicular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmVehicularActionPerformed(evt);
            }
        });
        JMAsignacion.add(JmVehicular);

        JMBMenu.add(JMAsignacion);

        JMProveedores.setText("Proveedores");

        JMBuscarP.setText("Buscar");

        jMenuItem1.setText("Proveedor ");
        JMBuscarP.add(jMenuItem1);

        JMCompraP.setText("Buscar Compra");
        JMBuscarP.add(JMCompraP);

        JMProveedores.add(JMBuscarP);

        jMenuItem2.setText("Agregar Proveedor");
        JMProveedores.add(jMenuItem2);

        JMBMenu.add(JMProveedores);

        JMCompras.setText("Compras");

        JMCompraM.setText("Compras");

        JMElaborar.setText("Elaborar");
        JMCompraM.add(JMElaborar);

        JMCompras.add(JMCompraM);

        JMBMenu.add(JMCompras);

        JmRMotos.setText("Registro Vehicular");

        JmiRegistrarM.setText("Registrar");
        JmiRegistrarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmiRegistrarMActionPerformed(evt);
            }
        });
        JmRMotos.add(JmiRegistrarM);

        JMBMenu.add(JmRMotos);

        setJMenuBar(JMBMenu);
        JMBMenu.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 872, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMAltaEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMAltaEActionPerformed
        //llamar a pagina Registro 
        Registro reg = new Registro();
        reg.setVisible(true);
    }//GEN-LAST:event_JMAltaEActionPerformed

    private void JMCrearMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMCrearMActionPerformed
        //llamar a pagina Mantenimiento 
        Mantenimientos Man = new Mantenimientos();
        Man.setVisible(true);
    }//GEN-LAST:event_JMCrearMActionPerformed

    private void JmiRegistrarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmiRegistrarMActionPerformed
        // llamar a pagina registro de motos 
        RegistroMotos RegM = new RegistroMotos();
        RegM.setVisible(true);
    }//GEN-LAST:event_JmiRegistrarMActionPerformed

    private void JmVehicularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmVehicularActionPerformed
        // llamar panatalla de asignacion vehicula
        Asiganacion Asg = new Asiganacion();
        Asg.setVisible(true);
    }//GEN-LAST:event_JmVehicularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuMantenimiento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JMAltaE;
    private javax.swing.JMenu JMAsignacion;
    private javax.swing.JMenuBar JMBMenu;
    private javax.swing.JMenu JMBuscarP;
    private javax.swing.JMenu JMCompraM;
    private javax.swing.JMenuItem JMCompraP;
    private javax.swing.JMenu JMCompras;
    private javax.swing.JMenuItem JMCrearM;
    private javax.swing.JMenuItem JMElaborar;
    private javax.swing.JMenu JMMantenimiento;
    private javax.swing.JMenu JMProveedores;
    private javax.swing.JMenu JMRegistro;
    private javax.swing.JDesktopPane JPMenu;
    private javax.swing.JMenu JmRMotos;
    private javax.swing.JMenuItem JmVehicular;
    private javax.swing.JMenuItem JmiRegistrarM;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    // End of variables declaration//GEN-END:variables
}
