/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mantenimiento;

import java.io.ByteArrayOutputStream;
import javax.swing.ImageIcon;
import net.glxn.qrgen.QRCode;
import net.glxn.qrgen.image.ImageType;
/**
 *
 * @author axel
 */
public class RegistroMotos extends javax.swing.JFrame {

    /**
     * Creates new form RegistroMotos
     */
    public RegistroMotos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblRegistroM = new javax.swing.JLabel();
        LblMarcaM = new javax.swing.JLabel();
        jtMarcaM = new javax.swing.JTextField();
        LblModeloM = new javax.swing.JLabel();
        jtModeloM = new javax.swing.JTextField();
        lblNumeroM = new javax.swing.JLabel();
        jtNumeroM = new javax.swing.JTextField();
        lblAño = new javax.swing.JLabel();
        jtAño = new javax.swing.JTextField();
        LblPlaca = new javax.swing.JLabel();
        JtPlaca = new javax.swing.JTextField();
        LblColor = new javax.swing.JLabel();
        JtColor = new javax.swing.JTextField();
        LblNSerie = new javax.swing.JLabel();
        JtNSerie = new javax.swing.JTextField();
        lblQR = new javax.swing.JLabel();
        BtnAceptar = new javax.swing.JButton();
        BtnCancelar = new javax.swing.JButton();
        btnGenerarQR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro de Motos");

        LblRegistroM.setText("Registro de Motos");

        LblMarcaM.setText("Marca:");

        LblModeloM.setText("Modelo:");

        lblNumeroM.setText("Numero de Moto:");

        lblAño.setText("Año:");

        LblPlaca.setText("Placa:");
        LblPlaca.setToolTipText("");

        LblColor.setText("Color:");

        LblNSerie.setText("Numero de Serie:");

        BtnAceptar.setText("Aceptar");

        BtnCancelar.setText("Cancelar");
        BtnCancelar.setToolTipText("");

        btnGenerarQR.setText("Generar QR");
        btnGenerarQR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarQRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LblMarcaM)
                                .addGap(18, 18, 18)
                                .addComponent(jtMarcaM, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(LblModeloM)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtAño, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtModeloM, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNumeroM)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtNumeroM, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(lblAño))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LblNSerie)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JtNSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(LblRegistroM))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LblPlaca)
                        .addGap(18, 18, 18)
                        .addComponent(JtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(LblColor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JtColor, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(BtnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(BtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblQR, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(btnGenerarQR)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblRegistroM)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblMarcaM)
                    .addComponent(jtMarcaM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblModeloM)
                    .addComponent(jtModeloM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeroM)
                    .addComponent(jtNumeroM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAño)
                    .addComponent(jtAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblPlaca)
                    .addComponent(JtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblColor)
                    .addComponent(JtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblNSerie)
                    .addComponent(JtNSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAceptar)
                    .addComponent(BtnCancelar))
                .addGap(18, 18, 18)
                .addComponent(lblQR, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGenerarQR)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarQRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarQRActionPerformed
        //Tomar los datos de los campos para la asignacion de moto
        ByteArrayOutputStream Ma = QRCode.from(this.jtMarcaM.getText()).to(ImageType.PNG).stream();
        ByteArrayOutputStream  Mo= QRCode.from(this.jtModeloM.getText()).to(ImageType.PNG).stream();
        //ByteArrayOutputStream  Nm= QRCode.from(this.jtNumeroM.getText()).to(ImageType.PNG).stream();
        //ByteArrayOutputStream  An= QRCode.from(this.jtAño.getText()).to(ImageType.PNG).stream();
        //ByteArrayOutputStream  Plc= QRCode.from(this.JtPlaca.getText()).to(ImageType.PNG).stream();
        //ByteArrayOutputStream  Clr= QRCode.from(this.JtColor.getText()).to(ImageType.PNG).stream();
        //ByteArrayOutputStream  Ns= QRCode.from(this.JtNSerie.getText()).to(ImageType.PNG).stream();
        //colocar los datos dentro de la imagen del QR
        ImageIcon Ma1 = new ImageIcon(Ma.toByteArray());
        ImageIcon Mo1 = new ImageIcon(Mo.toByteArray());
        //ImageIcon Nm1 = new ImageIcon(Nm.toByteArray());
        //ImageIcon An1 = new ImageIcon(An.toByteArray());
        //ImageIcon Plc1 = new ImageIcon(Plc.toByteArray());
        //ImageIcon Clr1 = new ImageIcon(Clr.toByteArray());
        //ImageIcon Ns1 = new ImageIcon(Ns.toByteArray());
        
        this.lblQR.setIcon(Ma1,"+",Mo1);
    }//GEN-LAST:event_btnGenerarQRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroMotos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroMotos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroMotos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroMotos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroMotos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAceptar;
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JTextField JtColor;
    private javax.swing.JTextField JtNSerie;
    private javax.swing.JTextField JtPlaca;
    private javax.swing.JLabel LblColor;
    private javax.swing.JLabel LblMarcaM;
    private javax.swing.JLabel LblModeloM;
    private javax.swing.JLabel LblNSerie;
    private javax.swing.JLabel LblPlaca;
    private javax.swing.JLabel LblRegistroM;
    private javax.swing.JButton btnGenerarQR;
    private javax.swing.JTextField jtAño;
    private javax.swing.JTextField jtMarcaM;
    private javax.swing.JTextField jtModeloM;
    private javax.swing.JTextField jtNumeroM;
    private javax.swing.JLabel lblAño;
    private javax.swing.JLabel lblNumeroM;
    private javax.swing.JLabel lblQR;
    // End of variables declaration//GEN-END:variables
}
